holgern/pyedflib

pyedflib/_extensions/c/edflib.c
setup.py

Hi!
If you tried to write an EDF file on an amd64 machine (and possible even any other machine) using this Python module, you ran into a segmentation fault:
```
Program received signal SIGSEGV, Segmentation fault.
__GI_rewind (fp=fp@entry=0x566f34a0) at rewind.c:34
34      rewind.c: Datei oder Verzeichnis nicht gefunden.
#0  __GI_rewind (fp=fp@entry=0x566f34a0) at rewind.c:34
#1  0x00007fffec7471bb in edflib_write_edf_header (hdr=hdr@entry=0x555556789bb0) at pyedflib/_extensions/c/edflib.c:4873
#2  0x00007fffec74c3ea in edf_blockwrite_physical_samples (handle=handle@entry=0, buf=<optimized out>)
at pyedflib/_extensions/c/edflib.c:4710
```
This happens because the `fopen64` and other functions are not defined. The compiler even warns about that and I thought about making that warning fatal …

Don't crash when writing files on 64bit machines

---

pyedflib/edfwriter.py

when writing an edf file, the gender defaults to 0, and birthday to 1900. in the case where the patient identity has been removed, this is misleading.

remove default gender and birthday

---

pyedflib/edfreader.py

Based on the call to s.decode, it looks like the intent here is to use the utf-8 codec. Failure to specify this explicitly in the unicode() call was causing exceptions for me when reading annotations from a file that had non-ASCII characters in them

Add utf-8 codec argument to unicode call in _convert_string

---

pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

Extended the writer to write digital samples instead of physical samples, as suggested in #6 .
`pyEDFWriter.writeSamples(data_list, digital=True)` will now accept digital raw values and not convert them.
No idea if this complies with your code standards or if it makes sense at all.
It's a small patch I've written and it seems to work well.
added some tests as well.

Included digital support

---

pyproject.toml

Include a `pyproject.toml` file with support for PEP 517 and 518. Without this support, pyEDFlib cannot be used within a project which follows PEP 517 and 518.

Add support for PEP 517 & 518

---

appveyor.yml
circle.yml
setup.py

using setuptools `dist.Distribution().fetch_build_eggs`, install numpy if it's not already found installed. This is with respect to #72 earlier opened

Install Numpy during installation and not fail when not installed

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/highlevel.py
pyedflib/tests/test_edfreader.py
pyedflib/tests/test_highlevel.py

There seem to be persistent problems with accented characters on Linux and Windows.
The initial #21 was fixed, however it still poses a problem as seen in #30 and #57 . Additionally, I also have problems on my Windows machine with Umlauts.
I reverted the changes proposed in #21 and switched back to UTF8-encoding of files. It seems to work now.
@holgern If errors continue, we can revert this commit again.

Reading of files with accented chars

---

doc/source/conf.py
doc/source/index.rst

Hey @holgern,
thanks for this toolbox. I just went through to find whether it has what I need (anonymization of EDF files), and fixed some formatting issues on your docs website on the way.
Hope that it's helpful.
PS: the `sphinx.ext.viewcode` extension provides a nice "View code" link next to the API documentation, to allow users to directly jump to viewing the sourcecode. looks a bit like here: 
(see turqouise SOURCE link in this screenshot)
try interactively here:
https://mne.tools/mne-bids/dev/generated/mne_bids.write_raw_bids.html#mne_bids.write_raw_bids

Fix links and formatting of index.rst, start using sphinx.ext.viewcode

---

pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_edfwriter.py

I've noticed that if physical_min and physical_max are equal, write_samples fails with error -25. An assertion before writing can help the user in understanding the issue

Assert that physical_min is different from physical_max

---

pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

I've implemented automatic setting of the blocksize, it will default to the highest `int` divisor below 60. As far as I can see `datarecord_duration` is in fact a float and could be set to any value, however, I'm a bit afraid that this will introduce side effects and rounding errors that result in loss of samples.
I did not want to include a manual trim while loading, as other EDF loading software does not implement that. However, the `block_size` parameter can be set manually if people do not mind having padded zeros at the end.
related: #92 
@holgern can you check, approve and possibly make a new release?

Automatically set blocksize // speed up writing

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/_extensions/c/edflib.c
pyedflib/tests/test_highlevel.py
pyproject.toml

This PR adds workarounds on Windows systems that are not using UTF8. Unicode filenames and Windows are quite a pain, and do not interact well with each other, unless UTF8 encoding is set as a windows locale (available on Windows 10). The problem is that `edflib` uses `fopen` - which on Windows (unlike Unix) can only accept 7/8-bit ANSI filenames. There is a function `_wopen` for Windows that is able to use multibyte characters (= Unicode), but it is unavailable on other OSs, and therefore we would need to implement OS-specific handling of `fopen`, which might introduce unwanted side effects. This caveat has been discussed at many places, e.g. here: https://stackoverflow.com/questions/53240475/non-ascii-filename-for-fopen
I tried opening the file in Cython as a FILE pointer and passing …

adding unicode read/write tests + workaround windows unicode files

---

pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

Check if header fields exceed 80 chars, and check for spaces and ascii in header field strings

add warnings for header length

---

README.rst
pyedflib/edfwriter.py
pyedflib/highlevel.py

When arrays are either in Fortran order or of mixed order, the writing will take substantially longer. Therefore, a warning will be displayed if input arrays are in Fortran order. When using the highlevel interface to write, automatic convertion is applied.
See #92 and #105

Prevent fortran layout

---

pyedflib/edfreader.py
pyedflib/highlevel.py
pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py

Currently while reading EDF files sample rates were rounded to int. We should allow decimal sample rates while also preventing float-rounding-errors of sample rates like 199.9999. I assume rounding to three decimals should be sufficient.
closes #109

Round sample rates up to 3 decimals not to int

---

pyedflib/highlevel.py

HI,
I found a bug while using rename_channel function. I believe wrong variable was used to call read_edf function. I changed it to following:
`    for ch_nr in tqdm(range(len(channels))):
signal, signal_header, _ = read_edf(edf_file, digital=True,
ch_nrs=ch_nr, verbose=False)`
Hope it helps!

fixed wrong variable use in rename_channel function

---

pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

fixes #119 
I changed the way annotations are loaded slightly, and there is an explicit type conversion happening now
I also use the internal function `readAnnotations` instead of the Cython `read_annotations`, which already has all the type conversions that are needed. This should have been the way anyway.

Fix annotation bytestring

---

.travis.yml
appveyor.yml
dev-requirements.txt
requirements-test.txt
tox.ini
travis/build-wheels.sh
util/readthedocs/requirements.txt
util/travis_osx_install.sh

I did three things:
1. remove matplotlib from the dependencies. it is only used in the `demo` folders, which I actually never looked at and I don't think is really used
2. remove `MANYLINUX=1` flags, which made travis build numpy from scratch, which failed. Now the github actions and travis should work again
3. remove `brew update`, as it's probably not necessary, and takes a long time
@holgern can you double check this is all good?

Cleanup travis buildscript

---

pyedflib/edfwriter.py

Ran into an issue on Ubuntu and Windows that would cause edfWriter to wither hang or crash and return `IOError('Unknown error while calling blockWriteSamples')` (edfWriter.py:741). Investigated and found this occurs if `len(data_list) == 0` in `edfWriter.writeSamples()`.
Added another conditional for this on line 693 to save future users effort in debugging.

non-empty data check in edfwriter to prevent unknown OS error

---

README.rst
demo/writeEDFFile.py
pyedflib/_extensions/_pyedflib.pyx
pyedflib/edfreader.py
pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_edfreader.py
pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py

Resolves #117 
The terms 'sample_rate' and 'sample_frequency' were used
interchangeably in the codebase, which is valid as long as the
record duration is 1 second, but they stop being the same when
the record duration is any other value. I followed the meaning
established in the documentation, where 'sample_frequency' is
taken to represent the number of samples per signal per record,
and 'sample_rate' is the number samples per signal per second.
This represents a breaking change to pyedflib's API, as it changes
the name of various EdfWriter method parameters and keys
in the signal dictionaries returned by EdfReader methods.
However, it conforms to the terminology used in the EDF spec
(that the header displays the number of samples in each data
record) as well as edflib function names.

Fix sample frequencies for record duration != 1

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/tests/test_edfreader.py

I split up the generic `OSError` into FileNotFoundError and OSError.
The first one is only given if the file really does not exist. The second is given in all other cases, such as wrong formatting or UTF8-filename errors on Windows
fixes #133

split up Errors in FileNotFoundError and OSError

---

pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py

just remove the warnings that the tests give.
add a catch to the warnings, so that we can make sure that they are displayed

suppress warnings in tests

---

pyedflib/_extensions/c/edflib.c

I'm trying to load EDF file from this dataset: https://physionet.org/content/eegmmidb
In these files, prefilter settings are present in both the normal fields and also in the EDF+ annotations.
For some reason, it was decided that pyedflib should flat out refuse to read such files?
I think that is a bit harsch.

Be less strict about prefilter fields

---

pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

Referencing discussion in #92 all Fortran-contiguous arrays are transformed before writing. This vastly improves write speed for this kind of arrays.

improved speedup write with F-contiguous arrays

---

README.rst

1. Adds "alt" text to each badge that shows up when the SVG cannot be loaded
2. removes one of the two conda badges, which was simply pointing to the conda-forge repository (all packages therein):  https://conda.anaconda.org/conda-forge  
3. replaces the pyedflib-specific conda-forge badge with one that explicitly says that this package is on conda-forge
4. Adds a PyPI badge next to the conda badge
Before:
After:

fix badges, add pypi badge

---

README.rst

it seems like the bitbucket link is broken. Maybe @cleemesser migrated his bitbucket repo to github at some point.
see also his "release note" here: https://github.com/cleemesser/python-edf/releases/tag/0.82

fix link bitbucket -> github

---

pyedflib/highlevel.py
pyedflib/tests/test_edfwriter.py

`np.float` is a deprecated alias for the builtin `float`. Deprecated in NumPy 1.20; for more details: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

np.float is deprecated

---

pyedflib/edfwriter.py

Executing the example code for writing an edf file via the highlevel interface:
```python
import numpy as np
from pyedflib import highlevel
signals = np.random.rand(5, 256*300)*200
channel_names = ['ch1', 'ch2', 'ch3', 'ch4', 'ch5']
signal_headers = highlevel.make_signal_headers(channel_names, sample_frequency=256)
header = highlevel.make_header(patientname='patient_x', gender='Female')
highlevel.write_edf('edf_file.edf', signals, signal_headers, header)
```
causes the following warning to be issued, even though the array is in C-order:
`UserWarning: signals are in Fortran order. Will automatically transfer to C order for compatibility with edflib.`
This is because the [check for fortran order](https://github.com/holgern/pyedflib/blob/master/pyedflib/edfwriter.py#L788:L789) iterates over …

Fix false positive fortran order warning

---

pyproject.toml

There is no guarantee that a specified numpy version has a wheel package for any given python version. By relaxing the numpy version limit, pip will fetch the available numpy wheel package, instead of trying to build the specific numpy version (which may fail to complete).

Remove limit on numpy version

---

.github/workflows/wheels.yml

As mentioned in #153, it would be great if a new release with Python 3.10 wheels could be made. This PR adds wheels for aarch64.

Build Python 3.10 wheels for aarch64

---

pyedflib/_extensions/c/edflib.c

replace lines in accordance with edflib 121

---

pyproject.toml

In the v0.1.24 release, pyedflib's cython extension was compiled against Numpy 1.22.1 for Python versions >=3.8 ([see workflow](https://github.com/holgern/pyedflib/runs/4894478892?check_suite_focus=true#step:5:2129)). Trying to import pyedflib in a local environment with a lower minor NumPy version (e.g. 1.21.5) leads to the cython error message shown in #156. 
The discussion on the introduction of an ndarray size change in NumPy 1.20.0 ([link](https://github.com/numpy/numpy/pull/16938)) contains a suggestion to use [`oldest-supported-numpy`](https://pypi.org/project/oldest-supported-numpy/) for building C/cython extensions.
I'm not sure why this error appears at the switch between 1.21 and 1.22 as the size change was introduced in 1.20 and have only tested this on Python 3.10 (Win10, …

use oldest-supported-numpy to build

---

.github/workflows/tests.yml

The Windows 2016 environment is deprecated, consider switching to windows-2019 or windows-2022 (windows-latest). For more details, see https://github.com/actions/virtual-environments/issues/4312
changed to 2019

change win2016 to win2019 as its deprecated

---

pyedflib/_extensions/_pyedflib.pyx

There was a `mode` parameter that seems to have been a leftover of a previous refactor. It was not used indeed as pointed out by #171 so it should be safe to remove.

remove deprecated "mode" parameter

---

pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

drop_channels forces the target to EDF+ but it should allow you to choose the file type.

Allow file_type option in drop_channels

---

.github/workflows/wheels.yml
doc/source/index.rst
setup.py

- [README.rst](https://github.com/holgern/pyedflib/blob/master/README.rst) already states
> pyEDFlib can be used with [Python](http://python.org/) >=3.7.
- Python 3.5 [reached EOL](https://devguide.python.org/versions/) in 2020.
- Python 3.6 [reached EOL](https://devguide.python.org/versions/) in 2021.
- Python 3.5 is not (easily) available in CI runners.

3.7 <= Python <= 3.11

---

pyedflib/edfwriter.py

Functions `isstr` and `isbytestr` are not used any more.
They have become simple one-liners, to the point that I find using their code inline, instead of calling them, clearer. Deprecate them.

Discard Python 2 leftovers

---

pyedflib/__init__.py

Hi! Today's release of [numpy v1.25.0](https://github.com/numpy/numpy/releases/tag/v1.25.0) removed `numpy.testing.Tester` (see numpy/numpy#23041). This causes the corresponding import in pyedflib's in [`__init__.py`](https://github.com/holgern/pyedflib/blob/022bbe9c4d9ab18fa57106bec22fd513ccb857fd/pyedflib/__init__.py#L17) to fail. I think this is a remnant of pyedflib using nose for testing so it can likely be removed. If you prefer to keep it, I'd like to suggest introducing an upper bound for the required numpy version.

Remove dependency on the deprecated np.testing.Tester

---

.github/workflows/wheels.yml

`setup-python@v4` requires to specify a Python version.

add python 3.8 for wheel building

---

doc/source/dev/installing_build_dependencies.rst

[Canopy GUI end of life -- transition to the Enthought Deployment Manager (EDM) and Visual Studio Code](https://support.enthought.com/hc/en-us/articles/360038600051-Canopy-GUI-end-of-life-transition-to-the-Enthought-Deployment-Manager-EDM-and-Visual-Studio-Code)

Enthought Canopy → Deployment Manager

---

README-edflib.md
README.rst
doc/Makefile
doc/make.bat
doc/source/conf.py
doc/source/dev/installing_build_dependencies.rst
doc/source/dev/preparing_windows_build_environment.rst
doc/source/dev/testing.rst
doc/source/index.rst
pyedflib/_extensions/_pyedflib.pyx
pyedflib/_extensions/c/edflib.h
setup.py

I have not changed the links fixed by https://github.com/holgern/pyedflib/pull/217.

http:// → https://

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/edfreader.py
pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_edfreader.py
pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py

gender → sex

---

dev-requirements.txt
pyproject.toml
requirements-test.txt

With newest Cython version 3.0, something with finding the modules is broken. Until  we have time to dive for a solution, I propose this hotfix to set Cython<3. As the Build is done in its own env, this should have no impact on the base env that we are installing to, ie. no side-effects
See #233

hotfix Cython<3, else can't install

---

pyproject.toml

This dependency is automatically provided by `setuptools`(see https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a).

Remove wheel from pyproject.toml

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
setup.py

Maybe this already works, let's see.

Add support for Python 3.12

---

.gitignore
pyedflib/_extensions/_pyedflib.pyx
pyedflib/_extensions/c/fopen_utf8.c
pyedflib/_extensions/c/fopen_utf8.h
setup.py

This should fix file opening issue with non-ASCII characters in paths when local encoding is not UTF-8.

Patch edflib.c on Windows to enable opening UTF-8 encoded paths

---

dev-requirements.txt
pyedflib/_extensions/_pyedflib.pyx
pyproject.toml
requirements-test.txt

Fix a relative `cimport` and revert the commit that pinned `cython<3.0`.

Support Cython 3

---

.github/workflows/tests.yml
pyedflib/_extensions/_pyedflib.pyx
pyedflib/edfreader.py
pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_edfreader.py
pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py

As discussed in https://github.com/holgern/pyedflib/issues/247 , I deprecated `sample_rate` and replaced all of its occurences with `sample_frequency`.
Frequency is usually measured in Hz, which is defined per second and is most consistent with other libraries (e.g. `mne`).
**Summary**
- There are errors raised when users try to use `sample_rate` - this is to ensure everyone finds out about the change without googeling
- I added a new routine to calculate `record_duration` - it should find an optimal value if one exists and let users not worry about the `sample_rate` as it is defined in `edflib` but to simply sey `sample_frequency` and be done
- It's still possible to overwrite the value of `record_duration` if ppl actually need to for obscure reasons
Additionally, needed to deprecate 3.7 …

Deprecate sample_rate

---

pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py
setup.py

Converted assert's into warnings. 
Reason:
in many cases, storing an edf file fails because of roundoff errors: e.g. `phys_min -3565.82 vs. signal_min 3565.8200000000000006` will fail in write_edf (but shouldn't)

Converted assert of phys_min and phys_max into warnings

---

doc/source/dev/building_extension.rst
doc/source/dev/how_to_release.rst
doc/source/dev/index.rst
doc/source/dev/preparing_windows_build_environment.rst
doc/source/resources.rst
pyedflib/__init__.py
pyedflib/highlevel.py
setup.py
util/authors.py

Remove Python 2.7 leftovers

---

pyedflib/_extensions/c/edflib.c
pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

There seems to be a problem with writing uft8 chars, see https://github.com/holgern/pyedflib/issues/275
The problem was that chinese utf chars are multi byte encoded, however, the C extension sanitized all byte chars that are below value 32 (control chars). However, for multi byte, that is actually valid printable unicode. Simply removing this fixes the issue.
```c
for(i=0; ; i++) {
if(list_annot->annotation[i] == 0) {
break;
}
if(list_annot->annotation[i] < 32) {
list_annot->annotation[i] = '.';
}
}
```
fixes #275

WIP: Fix utf-8 character writing
