doc/source/index_header.rst

couple tweaks to the README demo to fix some typos that tripped me up initially

small updates to demo

---

.gitignore
pyedflib/edfreader.py
pyedflib/tests/test_edfreader.py

The self.n_channels variable does not exist, use self.signals_in_file instead.

Fix getSignalHeaders

---

README.md

I also verified that installing `pywavelets`was not enough to make pyedflib working.

Essentially corrected a typo in readme

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/_extensions/c_edf.pxd
pyedflib/edfwriter.py

set_number_of_annotation_signals

---

setup.py

It troublesome for pyedflib to be marked as a dependency for another software package, where I expect it to get installed in an otherwise clean python environment, primarily because of the numpy dependency.  Having the install fail because numpy module not found can frequently occur.
Pipenv is sometimes able to get around this by detecting the error and waiting a while and trying the install later, but `pip install -e .` for my [timeview application](https://github.com/j9ac9k/timeview) can fail.
Another python library seemed to run into the same issue, [simpletraj](https://github.com/arose/simpletraj/blob/master/setup.py) and they seemed to get it figured out.  I largely utilized their code (which they took the implementation from …

hoping to address setup-time numpy dependency

---

pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

Switch digital dtype to int32.

---

pyedflib/edfreader.py

Same change as in #6 but now for reading. Should not be a big change and should be backwards-compatible.

Added option to get digital samples

---

pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

added warnings of exceeding min/max

---

pyedflib/highlevel.py

I added some clarifications to the docstring of `anonymize_edf` (no change in code behavior).
When saving, my editor automatically removed all trailing whitespace in the document (that's why there are many marked lines of no visible changes)

improve docstr of anonymize_edf

---

pyedflib/_extensions/_pyedflib.pyx
pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

Add support for gender removal

---

pyedflib/highlevel.py
pyedflib/tests/test_highlevel.py

I added `verbose` option for all highlevel functions and set the default to False

Verbose options default to False

---

pyedflib/edfwriter.py

PR for #123 
Implements suggested changes in post, all tests confirmed passing.

updated edfWriter:setSignalHeaders to update default dicts instead of overwriting

---

pyedflib/edfwriter.py
pyedflib/tests/test_edfwriter.py

I added some warnings if physical_min and physical_max or digital_min and digital_max are out of bounds. Some of them raise exceptions as a critical loss of precision is to be expected.
additionally, a warning is given if entries of the signal headers are too long. However, it's just a warning as those get truncated automatically.
fixes #132

add warnings if dmin/dmax/pmin/pmax is out of bounds 

---

pyedflib/edfreader.py
pyedflib/tests/test_edfreader.py

Add an error message to be more verbose when accessing channels that are out of bounds
closes #129

Add index error for chn access in edfreader

---

.circleci/config.yml
.github/workflows/tests.yml
appveyor.yml

Added Python 3.10 to the test matrix.

Run tests on Python 3.10

---

setup.py

replace imp with imporlib

---

doc/source/index.rst

Seems to be a typo in the index RST

remove mention of wavelet in doc

---

.github/workflows/tests.yml

this should hopefully enable our test suit for PRs from forked repos

fix workflows for external PRs

---

doc/source/dev/installing_build_dependencies.rst
doc/source/dev/preparing_windows_build_environment.rst

**PR Summary**:
The PR contains a fix to the Sphinx broken hyperlink found in the docs.

fix: update sphinx resource hyperlink

---

.github/workflows/wheels.yml
setup.py

add x86_64 arm64 mac arm wheels

---

demo/plotEDFFile.py
demo/readEDFFile.py
demo/stacklineplot.py
demo/streamingEDFFile.py
demo/writeEDFFile.py
doc/source/conf.py
pyedflib/data/__init__.py
pyedflib/data/_readers.py
pyedflib/edfreader.py
pyedflib/edfwriter.py
pyedflib/highlevel.py
pyedflib/tests/test_doc.py
pyedflib/tests/test_edfreader.py
pyedflib/tests/test_edfwriter.py
pyedflib/tests/test_highlevel.py
setup.py
util/authors.py
util/gh_lists.py
util/refguide_check.py

Not that I necessarily agree with all [isort](https://pycqa.github.io/isort/) choices, but the result is consistent and readable imports

Apply isort

---

pyedflib/edfreader.py

> `[FURB138]: Consider using list comprehension`

Apply a refurb suggestion that does improve the code
